1) Generate an array of zeroes using inbuilt numpy function.

In [1]:
import numpy as np

a = np.zeros([3,3])
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

2) Run the given code and find the dot product of both arrays.

In [2]:
import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)
a.dot(b)

[[9 9 2 3]
 [7 5 9 2]
 [6 2 7 9]]
[[9 4 8]
 [5 8 7]
 [7 7 6]
 [3 3 8]]


array([[149, 131, 171],
       [157, 137, 161],
       [140, 116, 176]])

3)Read the csv file provided using pandas and display the first 5 entries

In [3]:
import pandas as pd
data = pd.read_csv('/content/data.csv')
data.head()

OBJECTID                        UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0        21        Fort Stevenson State Park  ...   0.000284   0.135641
1        22           Beaver Lake State Park  ...   0.000129   0.080067
2        23  Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3        24           Fort Ransom State Park  ...   0.000444   0.128733
4        25        Grahams Island State Park  ...   0.000469   0.125546

[5 rows x 6 columns]

4)Describe the data with all features.

In [4]:
data.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

5)Find the total count of missing values for each feature.

In [5]:
data.isnull().count()

OBJECTID       25
UNIT_NAME      25
DESCRIPTION    25
ACRES          25
SHAPE.AREA     25
SHAPE.LEN      25
dtype: int64

6)Display all the unique values from the 'DESCRIPTION’ column.

In [6]:
data['DESCRIPTION'].unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

7)Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.

In [7]:
data.groupby(['DESCRIPTION']).mean()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

8)Generate a random sample of 10 rows from the data.

In [9]:
i = int(np.random.randint(0,(len(data)-10)))
data.iloc[i:i+10,:]

OBJECTID                                   UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
11        32                      Sully Creek State Park  ...   0.000030   0.024016
12        35        Butte St. Paul State Recreation Area  ...   0.000025   0.022095
13        36       Crow Flies High State Recreation Area  ...   0.000120   0.050518
14        33                     Turtle River State Park  ...   0.000378   0.145220
15        34                   Lake Sakakawea State Park  ...   0.000357   0.191806
16        37                  Elkhorn State Natural Area  ...   0.000127   0.067082
17        38         Fahlgren Park State Recreation Area  ...   0.000010   0.013294
18        39             Gunlogson State Nature Preserve  ...   0.000048   0.040465
19        40  Head of the Mountain State Nature Preserve  ...   0.000034   0.033885
20        41           Missouri River State Natural Area  ...   0.000083   0.087192

[10 rows x 6 columns]

9)Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy.

In [10]:
nf = np.random.rand(25,1)
data['New_feature'] = nf
data

OBJECTID  ... New_feature
0         21  ...    0.758837
1         22  ...    0.536676
2         23  ...    0.988415
3         24  ...    0.927723
4         25  ...    0.890675
5         26  ...    0.105928
6         27  ...    0.262222
7         28  ...    0.265591
8         29  ...    0.341497
9         30  ...    0.419952
10        31  ...    0.279796
11        32  ...    0.370429
12        35  ...    0.895520
13        36  ...    0.463687
14        33  ...    0.172567
15        34  ...    0.177459
16        37  ...    0.546984
17        38  ...    0.339205
18        39  ...    0.415241
19        40  ...    0.332190
20        41  ...    0.933807
21        43  ...    0.339797
22        44  ...    0.186223
23        45  ...    0.290918
24        42  ...    0.088601

[25 rows x 7 columns]

10) Replace zero value of column 'OBJECTID' with mean value permanently.

In [11]:
data['OBJECTID'].replace(data.iloc[0,0], data['OBJECTID'].mean(), inplace=True)
data

OBJECTID  ... New_feature
0         33  ...    0.758837
1         22  ...    0.536676
2         23  ...    0.988415
3         24  ...    0.927723
4         25  ...    0.890675
5         26  ...    0.105928
6         27  ...    0.262222
7         28  ...    0.265591
8         29  ...    0.341497
9         30  ...    0.419952
10        31  ...    0.279796
11        32  ...    0.370429
12        35  ...    0.895520
13        36  ...    0.463687
14        33  ...    0.172567
15        34  ...    0.177459
16        37  ...    0.546984
17        38  ...    0.339205
18        39  ...    0.415241
19        40  ...    0.332190
20        41  ...    0.933807
21        43  ...    0.339797
22        44  ...    0.186223
23        45  ...    0.290918
24        42  ...    0.088601

[25 rows x 7 columns]